vaultPath: '/Users/samli/OneDrive/Notes/Samuel Lihn'
chromeExecutablePath: 'C:\Program Files\Google\Chrome\Application\chrome.exe'
exclude:
  - _freeview/*
  - weekly thoughts*
  - Portfolio/*
  - Daily Notes/*
  - Homework/*